/********************************************************************************/
/*                                                                              */
/* CZ80 JumpTable include source file                                           */
/* C Z80 emulator version 0.91                                                  */
/* Copyright 2004-2005 Stephane Dallongeville                                   */
/*                                                                              */
/********************************************************************************/

#ifndef IS_IN_CZ80
#error Do not compile this file by itself - compile cz80.c instead
#endif

// NOTE: Only enable on 64-bit or shared library builds.
// Otherwise, this just adds overhead.
#define CZ80_USE_RELATIVE_JUMPTABLE 0

#if CZ80_USE_RELATIVE_JUMPTABLE
typedef int CZ80_JMPTYPE;
#define JMPTBL(base, label) (&&label - &&base)
#define DO_JMPTBL(tbl, base, Opcode) goto *(&&base + tbl[Opcode])
#else
typedef void *CZ80_JMPTYPE;
#define JMPTBL(base, label) &&label
#define DO_JMPTBL(tbl, base, Opcode) goto *tbl[Opcode]
#endif

#define JMPLABEL_OP(label) JMPTBL(OP0x00, label)
#define DO_JMPTBL_OP(Opcode) DO_JMPTBL(JumpTable, OP0x00, Opcode)
static const CZ80_JMPTYPE JumpTable[0x100] = {
    JMPLABEL_OP(OP0x00), JMPLABEL_OP(OP0x01), JMPLABEL_OP(OP0x02), JMPLABEL_OP(OP0x03),
    JMPLABEL_OP(OP0x04), JMPLABEL_OP(OP0x05), JMPLABEL_OP(OP0x06), JMPLABEL_OP(OP0x07),
    JMPLABEL_OP(OP0x08), JMPLABEL_OP(OP0x09), JMPLABEL_OP(OP0x0a), JMPLABEL_OP(OP0x0b),
    JMPLABEL_OP(OP0x0c), JMPLABEL_OP(OP0x0d), JMPLABEL_OP(OP0x0e), JMPLABEL_OP(OP0x0f),

    JMPLABEL_OP(OP0x10), JMPLABEL_OP(OP0x11), JMPLABEL_OP(OP0x12), JMPLABEL_OP(OP0x13),
    JMPLABEL_OP(OP0x14), JMPLABEL_OP(OP0x15), JMPLABEL_OP(OP0x16), JMPLABEL_OP(OP0x17),
    JMPLABEL_OP(OP0x18), JMPLABEL_OP(OP0x19), JMPLABEL_OP(OP0x1a), JMPLABEL_OP(OP0x1b),
    JMPLABEL_OP(OP0x1c), JMPLABEL_OP(OP0x1d), JMPLABEL_OP(OP0x1e), JMPLABEL_OP(OP0x1f),

    JMPLABEL_OP(OP0x20), JMPLABEL_OP(OP0x21), JMPLABEL_OP(OP0x22), JMPLABEL_OP(OP0x23),
    JMPLABEL_OP(OP0x24), JMPLABEL_OP(OP0x25), JMPLABEL_OP(OP0x26), JMPLABEL_OP(OP0x27),
    JMPLABEL_OP(OP0x28), JMPLABEL_OP(OP0x29), JMPLABEL_OP(OP0x2a), JMPLABEL_OP(OP0x2b),
    JMPLABEL_OP(OP0x2c), JMPLABEL_OP(OP0x2d), JMPLABEL_OP(OP0x2e), JMPLABEL_OP(OP0x2f),

    JMPLABEL_OP(OP0x30), JMPLABEL_OP(OP0x31), JMPLABEL_OP(OP0x32), JMPLABEL_OP(OP0x33),
    JMPLABEL_OP(OP0x34), JMPLABEL_OP(OP0x35), JMPLABEL_OP(OP0x36), JMPLABEL_OP(OP0x37),
    JMPLABEL_OP(OP0x38), JMPLABEL_OP(OP0x39), JMPLABEL_OP(OP0x3a), JMPLABEL_OP(OP0x3b),
    JMPLABEL_OP(OP0x3c), JMPLABEL_OP(OP0x3d), JMPLABEL_OP(OP0x3e), JMPLABEL_OP(OP0x3f),

    JMPLABEL_OP(OP0x40), JMPLABEL_OP(OP0x41), JMPLABEL_OP(OP0x42), JMPLABEL_OP(OP0x43),
    JMPLABEL_OP(OP0x44), JMPLABEL_OP(OP0x45), JMPLABEL_OP(OP0x46), JMPLABEL_OP(OP0x47),
    JMPLABEL_OP(OP0x48), JMPLABEL_OP(OP0x49), JMPLABEL_OP(OP0x4a), JMPLABEL_OP(OP0x4b),
    JMPLABEL_OP(OP0x4c), JMPLABEL_OP(OP0x4d), JMPLABEL_OP(OP0x4e), JMPLABEL_OP(OP0x4f),

    JMPLABEL_OP(OP0x50), JMPLABEL_OP(OP0x51), JMPLABEL_OP(OP0x52), JMPLABEL_OP(OP0x53),
    JMPLABEL_OP(OP0x54), JMPLABEL_OP(OP0x55), JMPLABEL_OP(OP0x56), JMPLABEL_OP(OP0x57),
    JMPLABEL_OP(OP0x58), JMPLABEL_OP(OP0x59), JMPLABEL_OP(OP0x5a), JMPLABEL_OP(OP0x5b),
    JMPLABEL_OP(OP0x5c), JMPLABEL_OP(OP0x5d), JMPLABEL_OP(OP0x5e), JMPLABEL_OP(OP0x5f),

    JMPLABEL_OP(OP0x60), JMPLABEL_OP(OP0x61), JMPLABEL_OP(OP0x62), JMPLABEL_OP(OP0x63),
    JMPLABEL_OP(OP0x64), JMPLABEL_OP(OP0x65), JMPLABEL_OP(OP0x66), JMPLABEL_OP(OP0x67),
    JMPLABEL_OP(OP0x68), JMPLABEL_OP(OP0x69), JMPLABEL_OP(OP0x6a), JMPLABEL_OP(OP0x6b),
    JMPLABEL_OP(OP0x6c), JMPLABEL_OP(OP0x6d), JMPLABEL_OP(OP0x6e), JMPLABEL_OP(OP0x6f),

    JMPLABEL_OP(OP0x70), JMPLABEL_OP(OP0x71), JMPLABEL_OP(OP0x72), JMPLABEL_OP(OP0x73),
    JMPLABEL_OP(OP0x74), JMPLABEL_OP(OP0x75), JMPLABEL_OP(OP0x76), JMPLABEL_OP(OP0x77),
    JMPLABEL_OP(OP0x78), JMPLABEL_OP(OP0x79), JMPLABEL_OP(OP0x7a), JMPLABEL_OP(OP0x7b),
    JMPLABEL_OP(OP0x7c), JMPLABEL_OP(OP0x7d), JMPLABEL_OP(OP0x7e), JMPLABEL_OP(OP0x7f),

    JMPLABEL_OP(OP0x80), JMPLABEL_OP(OP0x81), JMPLABEL_OP(OP0x82), JMPLABEL_OP(OP0x83),
    JMPLABEL_OP(OP0x84), JMPLABEL_OP(OP0x85), JMPLABEL_OP(OP0x86), JMPLABEL_OP(OP0x87),
    JMPLABEL_OP(OP0x88), JMPLABEL_OP(OP0x89), JMPLABEL_OP(OP0x8a), JMPLABEL_OP(OP0x8b),
    JMPLABEL_OP(OP0x8c), JMPLABEL_OP(OP0x8d), JMPLABEL_OP(OP0x8e), JMPLABEL_OP(OP0x8f),

    JMPLABEL_OP(OP0x90), JMPLABEL_OP(OP0x91), JMPLABEL_OP(OP0x92), JMPLABEL_OP(OP0x93),
    JMPLABEL_OP(OP0x94), JMPLABEL_OP(OP0x95), JMPLABEL_OP(OP0x96), JMPLABEL_OP(OP0x97),
    JMPLABEL_OP(OP0x98), JMPLABEL_OP(OP0x99), JMPLABEL_OP(OP0x9a), JMPLABEL_OP(OP0x9b),
    JMPLABEL_OP(OP0x9c), JMPLABEL_OP(OP0x9d), JMPLABEL_OP(OP0x9e), JMPLABEL_OP(OP0x9f),

    JMPLABEL_OP(OP0xa0), JMPLABEL_OP(OP0xa1), JMPLABEL_OP(OP0xa2), JMPLABEL_OP(OP0xa3),
    JMPLABEL_OP(OP0xa4), JMPLABEL_OP(OP0xa5), JMPLABEL_OP(OP0xa6), JMPLABEL_OP(OP0xa7),
    JMPLABEL_OP(OP0xa8), JMPLABEL_OP(OP0xa9), JMPLABEL_OP(OP0xaa), JMPLABEL_OP(OP0xab),
    JMPLABEL_OP(OP0xac), JMPLABEL_OP(OP0xad), JMPLABEL_OP(OP0xae), JMPLABEL_OP(OP0xaf),

    JMPLABEL_OP(OP0xb0), JMPLABEL_OP(OP0xb1), JMPLABEL_OP(OP0xb2), JMPLABEL_OP(OP0xb3),
    JMPLABEL_OP(OP0xb4), JMPLABEL_OP(OP0xb5), JMPLABEL_OP(OP0xb6), JMPLABEL_OP(OP0xb7),
    JMPLABEL_OP(OP0xb8), JMPLABEL_OP(OP0xb9), JMPLABEL_OP(OP0xba), JMPLABEL_OP(OP0xbb),
    JMPLABEL_OP(OP0xbc), JMPLABEL_OP(OP0xbd), JMPLABEL_OP(OP0xbe), JMPLABEL_OP(OP0xbf),

    JMPLABEL_OP(OP0xc0), JMPLABEL_OP(OP0xc1), JMPLABEL_OP(OP0xc2), JMPLABEL_OP(OP0xc3),
    JMPLABEL_OP(OP0xc4), JMPLABEL_OP(OP0xc5), JMPLABEL_OP(OP0xc6), JMPLABEL_OP(OP0xc7),
    JMPLABEL_OP(OP0xc8), JMPLABEL_OP(OP0xc9), JMPLABEL_OP(OP0xca), JMPLABEL_OP(OP0xcb),
    JMPLABEL_OP(OP0xcc), JMPLABEL_OP(OP0xcd), JMPLABEL_OP(OP0xce), JMPLABEL_OP(OP0xcf),

    JMPLABEL_OP(OP0xd0), JMPLABEL_OP(OP0xd1), JMPLABEL_OP(OP0xd2), JMPLABEL_OP(OP0xd3),
    JMPLABEL_OP(OP0xd4), JMPLABEL_OP(OP0xd5), JMPLABEL_OP(OP0xd6), JMPLABEL_OP(OP0xd7),
    JMPLABEL_OP(OP0xd8), JMPLABEL_OP(OP0xd9), JMPLABEL_OP(OP0xda), JMPLABEL_OP(OP0xdb),
    JMPLABEL_OP(OP0xdc), JMPLABEL_OP(OP0xdd), JMPLABEL_OP(OP0xde), JMPLABEL_OP(OP0xdf),

    JMPLABEL_OP(OP0xe0), JMPLABEL_OP(OP0xe1), JMPLABEL_OP(OP0xe2), JMPLABEL_OP(OP0xe3),
    JMPLABEL_OP(OP0xe4), JMPLABEL_OP(OP0xe5), JMPLABEL_OP(OP0xe6), JMPLABEL_OP(OP0xe7),
    JMPLABEL_OP(OP0xe8), JMPLABEL_OP(OP0xe9), JMPLABEL_OP(OP0xea), JMPLABEL_OP(OP0xeb),
    JMPLABEL_OP(OP0xec), JMPLABEL_OP(OP0xed), JMPLABEL_OP(OP0xee), JMPLABEL_OP(OP0xef),

    JMPLABEL_OP(OP0xf0), JMPLABEL_OP(OP0xf1), JMPLABEL_OP(OP0xf2), JMPLABEL_OP(OP0xf3),
    JMPLABEL_OP(OP0xf4), JMPLABEL_OP(OP0xf5), JMPLABEL_OP(OP0xf6), JMPLABEL_OP(OP0xf7),
    JMPLABEL_OP(OP0xf8), JMPLABEL_OP(OP0xf9), JMPLABEL_OP(OP0xfa), JMPLABEL_OP(OP0xfb),
    JMPLABEL_OP(OP0xfc), JMPLABEL_OP(OP0xfd), JMPLABEL_OP(OP0xfe), JMPLABEL_OP(OP0xff)
};

#define JMPLABEL_OPCB(label) JMPTBL(OPCB0x00, label)
#define DO_JMPTBL_OPCB(Opcode) DO_JMPTBL(JumpTableCB, OPCB0x00, Opcode)
static const CZ80_JMPTYPE JumpTableCB[0x100] = {
    JMPLABEL_OPCB(OPCB0x00), JMPLABEL_OPCB(OPCB0x01), JMPLABEL_OPCB(OPCB0x02), JMPLABEL_OPCB(OPCB0x03),
    JMPLABEL_OPCB(OPCB0x04), JMPLABEL_OPCB(OPCB0x05), JMPLABEL_OPCB(OPCB0x06), JMPLABEL_OPCB(OPCB0x07),
    JMPLABEL_OPCB(OPCB0x08), JMPLABEL_OPCB(OPCB0x09), JMPLABEL_OPCB(OPCB0x0a), JMPLABEL_OPCB(OPCB0x0b),
    JMPLABEL_OPCB(OPCB0x0c), JMPLABEL_OPCB(OPCB0x0d), JMPLABEL_OPCB(OPCB0x0e), JMPLABEL_OPCB(OPCB0x0f),

    JMPLABEL_OPCB(OPCB0x10), JMPLABEL_OPCB(OPCB0x11), JMPLABEL_OPCB(OPCB0x12), JMPLABEL_OPCB(OPCB0x13),
    JMPLABEL_OPCB(OPCB0x14), JMPLABEL_OPCB(OPCB0x15), JMPLABEL_OPCB(OPCB0x16), JMPLABEL_OPCB(OPCB0x17),
    JMPLABEL_OPCB(OPCB0x18), JMPLABEL_OPCB(OPCB0x19), JMPLABEL_OPCB(OPCB0x1a), JMPLABEL_OPCB(OPCB0x1b),
    JMPLABEL_OPCB(OPCB0x1c), JMPLABEL_OPCB(OPCB0x1d), JMPLABEL_OPCB(OPCB0x1e), JMPLABEL_OPCB(OPCB0x1f),

    JMPLABEL_OPCB(OPCB0x20), JMPLABEL_OPCB(OPCB0x21), JMPLABEL_OPCB(OPCB0x22), JMPLABEL_OPCB(OPCB0x23),
    JMPLABEL_OPCB(OPCB0x24), JMPLABEL_OPCB(OPCB0x25), JMPLABEL_OPCB(OPCB0x26), JMPLABEL_OPCB(OPCB0x27),
    JMPLABEL_OPCB(OPCB0x28), JMPLABEL_OPCB(OPCB0x29), JMPLABEL_OPCB(OPCB0x2a), JMPLABEL_OPCB(OPCB0x2b),
    JMPLABEL_OPCB(OPCB0x2c), JMPLABEL_OPCB(OPCB0x2d), JMPLABEL_OPCB(OPCB0x2e), JMPLABEL_OPCB(OPCB0x2f),

    JMPLABEL_OPCB(OPCB0x30), JMPLABEL_OPCB(OPCB0x31), JMPLABEL_OPCB(OPCB0x32), JMPLABEL_OPCB(OPCB0x33),
    JMPLABEL_OPCB(OPCB0x34), JMPLABEL_OPCB(OPCB0x35), JMPLABEL_OPCB(OPCB0x36), JMPLABEL_OPCB(OPCB0x37),
    JMPLABEL_OPCB(OPCB0x38), JMPLABEL_OPCB(OPCB0x39), JMPLABEL_OPCB(OPCB0x3a), JMPLABEL_OPCB(OPCB0x3b),
    JMPLABEL_OPCB(OPCB0x3c), JMPLABEL_OPCB(OPCB0x3d), JMPLABEL_OPCB(OPCB0x3e), JMPLABEL_OPCB(OPCB0x3f),

    JMPLABEL_OPCB(OPCB0x40), JMPLABEL_OPCB(OPCB0x41), JMPLABEL_OPCB(OPCB0x42), JMPLABEL_OPCB(OPCB0x43),
    JMPLABEL_OPCB(OPCB0x44), JMPLABEL_OPCB(OPCB0x45), JMPLABEL_OPCB(OPCB0x46), JMPLABEL_OPCB(OPCB0x47),
    JMPLABEL_OPCB(OPCB0x48), JMPLABEL_OPCB(OPCB0x49), JMPLABEL_OPCB(OPCB0x4a), JMPLABEL_OPCB(OPCB0x4b),
    JMPLABEL_OPCB(OPCB0x4c), JMPLABEL_OPCB(OPCB0x4d), JMPLABEL_OPCB(OPCB0x4e), JMPLABEL_OPCB(OPCB0x4f),

    JMPLABEL_OPCB(OPCB0x50), JMPLABEL_OPCB(OPCB0x51), JMPLABEL_OPCB(OPCB0x52), JMPLABEL_OPCB(OPCB0x53),
    JMPLABEL_OPCB(OPCB0x54), JMPLABEL_OPCB(OPCB0x55), JMPLABEL_OPCB(OPCB0x56), JMPLABEL_OPCB(OPCB0x57),
    JMPLABEL_OPCB(OPCB0x58), JMPLABEL_OPCB(OPCB0x59), JMPLABEL_OPCB(OPCB0x5a), JMPLABEL_OPCB(OPCB0x5b),
    JMPLABEL_OPCB(OPCB0x5c), JMPLABEL_OPCB(OPCB0x5d), JMPLABEL_OPCB(OPCB0x5e), JMPLABEL_OPCB(OPCB0x5f),

    JMPLABEL_OPCB(OPCB0x60), JMPLABEL_OPCB(OPCB0x61), JMPLABEL_OPCB(OPCB0x62), JMPLABEL_OPCB(OPCB0x63),
    JMPLABEL_OPCB(OPCB0x64), JMPLABEL_OPCB(OPCB0x65), JMPLABEL_OPCB(OPCB0x66), JMPLABEL_OPCB(OPCB0x67),
    JMPLABEL_OPCB(OPCB0x68), JMPLABEL_OPCB(OPCB0x69), JMPLABEL_OPCB(OPCB0x6a), JMPLABEL_OPCB(OPCB0x6b),
    JMPLABEL_OPCB(OPCB0x6c), JMPLABEL_OPCB(OPCB0x6d), JMPLABEL_OPCB(OPCB0x6e), JMPLABEL_OPCB(OPCB0x6f),

    JMPLABEL_OPCB(OPCB0x70), JMPLABEL_OPCB(OPCB0x71), JMPLABEL_OPCB(OPCB0x72), JMPLABEL_OPCB(OPCB0x73),
    JMPLABEL_OPCB(OPCB0x74), JMPLABEL_OPCB(OPCB0x75), JMPLABEL_OPCB(OPCB0x76), JMPLABEL_OPCB(OPCB0x77),
    JMPLABEL_OPCB(OPCB0x78), JMPLABEL_OPCB(OPCB0x79), JMPLABEL_OPCB(OPCB0x7a), JMPLABEL_OPCB(OPCB0x7b),
    JMPLABEL_OPCB(OPCB0x7c), JMPLABEL_OPCB(OPCB0x7d), JMPLABEL_OPCB(OPCB0x7e), JMPLABEL_OPCB(OPCB0x7f),

    JMPLABEL_OPCB(OPCB0x80), JMPLABEL_OPCB(OPCB0x81), JMPLABEL_OPCB(OPCB0x82), JMPLABEL_OPCB(OPCB0x83),
    JMPLABEL_OPCB(OPCB0x84), JMPLABEL_OPCB(OPCB0x85), JMPLABEL_OPCB(OPCB0x86), JMPLABEL_OPCB(OPCB0x87),
    JMPLABEL_OPCB(OPCB0x88), JMPLABEL_OPCB(OPCB0x89), JMPLABEL_OPCB(OPCB0x8a), JMPLABEL_OPCB(OPCB0x8b),
    JMPLABEL_OPCB(OPCB0x8c), JMPLABEL_OPCB(OPCB0x8d), JMPLABEL_OPCB(OPCB0x8e), JMPLABEL_OPCB(OPCB0x8f),

    JMPLABEL_OPCB(OPCB0x90), JMPLABEL_OPCB(OPCB0x91), JMPLABEL_OPCB(OPCB0x92), JMPLABEL_OPCB(OPCB0x93),
    JMPLABEL_OPCB(OPCB0x94), JMPLABEL_OPCB(OPCB0x95), JMPLABEL_OPCB(OPCB0x96), JMPLABEL_OPCB(OPCB0x97),
    JMPLABEL_OPCB(OPCB0x98), JMPLABEL_OPCB(OPCB0x99), JMPLABEL_OPCB(OPCB0x9a), JMPLABEL_OPCB(OPCB0x9b),
    JMPLABEL_OPCB(OPCB0x9c), JMPLABEL_OPCB(OPCB0x9d), JMPLABEL_OPCB(OPCB0x9e), JMPLABEL_OPCB(OPCB0x9f),

    JMPLABEL_OPCB(OPCB0xa0), JMPLABEL_OPCB(OPCB0xa1), JMPLABEL_OPCB(OPCB0xa2), JMPLABEL_OPCB(OPCB0xa3),
    JMPLABEL_OPCB(OPCB0xa4), JMPLABEL_OPCB(OPCB0xa5), JMPLABEL_OPCB(OPCB0xa6), JMPLABEL_OPCB(OPCB0xa7),
    JMPLABEL_OPCB(OPCB0xa8), JMPLABEL_OPCB(OPCB0xa9), JMPLABEL_OPCB(OPCB0xaa), JMPLABEL_OPCB(OPCB0xab),
    JMPLABEL_OPCB(OPCB0xac), JMPLABEL_OPCB(OPCB0xad), JMPLABEL_OPCB(OPCB0xae), JMPLABEL_OPCB(OPCB0xaf),

    JMPLABEL_OPCB(OPCB0xb0), JMPLABEL_OPCB(OPCB0xb1), JMPLABEL_OPCB(OPCB0xb2), JMPLABEL_OPCB(OPCB0xb3),
    JMPLABEL_OPCB(OPCB0xb4), JMPLABEL_OPCB(OPCB0xb5), JMPLABEL_OPCB(OPCB0xb6), JMPLABEL_OPCB(OPCB0xb7),
    JMPLABEL_OPCB(OPCB0xb8), JMPLABEL_OPCB(OPCB0xb9), JMPLABEL_OPCB(OPCB0xba), JMPLABEL_OPCB(OPCB0xbb),
    JMPLABEL_OPCB(OPCB0xbc), JMPLABEL_OPCB(OPCB0xbd), JMPLABEL_OPCB(OPCB0xbe), JMPLABEL_OPCB(OPCB0xbf),

    JMPLABEL_OPCB(OPCB0xc0), JMPLABEL_OPCB(OPCB0xc1), JMPLABEL_OPCB(OPCB0xc2), JMPLABEL_OPCB(OPCB0xc3),
    JMPLABEL_OPCB(OPCB0xc4), JMPLABEL_OPCB(OPCB0xc5), JMPLABEL_OPCB(OPCB0xc6), JMPLABEL_OPCB(OPCB0xc7),
    JMPLABEL_OPCB(OPCB0xc8), JMPLABEL_OPCB(OPCB0xc9), JMPLABEL_OPCB(OPCB0xca), JMPLABEL_OPCB(OPCB0xcb),
    JMPLABEL_OPCB(OPCB0xcc), JMPLABEL_OPCB(OPCB0xcd), JMPLABEL_OPCB(OPCB0xce), JMPLABEL_OPCB(OPCB0xcf),

    JMPLABEL_OPCB(OPCB0xd0), JMPLABEL_OPCB(OPCB0xd1), JMPLABEL_OPCB(OPCB0xd2), JMPLABEL_OPCB(OPCB0xd3),
    JMPLABEL_OPCB(OPCB0xd4), JMPLABEL_OPCB(OPCB0xd5), JMPLABEL_OPCB(OPCB0xd6), JMPLABEL_OPCB(OPCB0xd7),
    JMPLABEL_OPCB(OPCB0xd8), JMPLABEL_OPCB(OPCB0xd9), JMPLABEL_OPCB(OPCB0xda), JMPLABEL_OPCB(OPCB0xdb),
    JMPLABEL_OPCB(OPCB0xdc), JMPLABEL_OPCB(OPCB0xdd), JMPLABEL_OPCB(OPCB0xde), JMPLABEL_OPCB(OPCB0xdf),

    JMPLABEL_OPCB(OPCB0xe0), JMPLABEL_OPCB(OPCB0xe1), JMPLABEL_OPCB(OPCB0xe2), JMPLABEL_OPCB(OPCB0xe3),
    JMPLABEL_OPCB(OPCB0xe4), JMPLABEL_OPCB(OPCB0xe5), JMPLABEL_OPCB(OPCB0xe6), JMPLABEL_OPCB(OPCB0xe7),
    JMPLABEL_OPCB(OPCB0xe8), JMPLABEL_OPCB(OPCB0xe9), JMPLABEL_OPCB(OPCB0xea), JMPLABEL_OPCB(OPCB0xeb),
    JMPLABEL_OPCB(OPCB0xec), JMPLABEL_OPCB(OPCB0xed), JMPLABEL_OPCB(OPCB0xee), JMPLABEL_OPCB(OPCB0xef),

    JMPLABEL_OPCB(OPCB0xf0), JMPLABEL_OPCB(OPCB0xf1), JMPLABEL_OPCB(OPCB0xf2), JMPLABEL_OPCB(OPCB0xf3),
    JMPLABEL_OPCB(OPCB0xf4), JMPLABEL_OPCB(OPCB0xf5), JMPLABEL_OPCB(OPCB0xf6), JMPLABEL_OPCB(OPCB0xf7),
    JMPLABEL_OPCB(OPCB0xf8), JMPLABEL_OPCB(OPCB0xf9), JMPLABEL_OPCB(OPCB0xfa), JMPLABEL_OPCB(OPCB0xfb),
    JMPLABEL_OPCB(OPCB0xfc), JMPLABEL_OPCB(OPCB0xfd), JMPLABEL_OPCB(OPCB0xfe), JMPLABEL_OPCB(OPCB0xff)
};

#define JMPLABEL_OPED(label) JMPTBL(OPED0x00, label)
#define DO_JMPTBL_OPED(Opcode) DO_JMPTBL(JumpTableED, OPED0x00, Opcode)
static const CZ80_JMPTYPE JumpTableED[0x100] = {
    JMPLABEL_OPED(OPED0x00), JMPLABEL_OPED(OPED0x01), JMPLABEL_OPED(OPED0x02), JMPLABEL_OPED(OPED0x03),
    JMPLABEL_OPED(OPED0x04), JMPLABEL_OPED(OPED0x05), JMPLABEL_OPED(OPED0x06), JMPLABEL_OPED(OPED0x07),
    JMPLABEL_OPED(OPED0x08), JMPLABEL_OPED(OPED0x09), JMPLABEL_OPED(OPED0x0a), JMPLABEL_OPED(OPED0x0b),
    JMPLABEL_OPED(OPED0x0c), JMPLABEL_OPED(OPED0x0d), JMPLABEL_OPED(OPED0x0e), JMPLABEL_OPED(OPED0x0f),

    JMPLABEL_OPED(OPED0x10), JMPLABEL_OPED(OPED0x11), JMPLABEL_OPED(OPED0x12), JMPLABEL_OPED(OPED0x13),
    JMPLABEL_OPED(OPED0x14), JMPLABEL_OPED(OPED0x15), JMPLABEL_OPED(OPED0x16), JMPLABEL_OPED(OPED0x17),
    JMPLABEL_OPED(OPED0x18), JMPLABEL_OPED(OPED0x19), JMPLABEL_OPED(OPED0x1a), JMPLABEL_OPED(OPED0x1b),
    JMPLABEL_OPED(OPED0x1c), JMPLABEL_OPED(OPED0x1d), JMPLABEL_OPED(OPED0x1e), JMPLABEL_OPED(OPED0x1f),

    JMPLABEL_OPED(OPED0x20), JMPLABEL_OPED(OPED0x21), JMPLABEL_OPED(OPED0x22), JMPLABEL_OPED(OPED0x23),
    JMPLABEL_OPED(OPED0x24), JMPLABEL_OPED(OPED0x25), JMPLABEL_OPED(OPED0x26), JMPLABEL_OPED(OPED0x27),
    JMPLABEL_OPED(OPED0x28), JMPLABEL_OPED(OPED0x29), JMPLABEL_OPED(OPED0x2a), JMPLABEL_OPED(OPED0x2b),
    JMPLABEL_OPED(OPED0x2c), JMPLABEL_OPED(OPED0x2d), JMPLABEL_OPED(OPED0x2e), JMPLABEL_OPED(OPED0x2f),

    JMPLABEL_OPED(OPED0x30), JMPLABEL_OPED(OPED0x31), JMPLABEL_OPED(OPED0x32), JMPLABEL_OPED(OPED0x33),
    JMPLABEL_OPED(OPED0x34), JMPLABEL_OPED(OPED0x35), JMPLABEL_OPED(OPED0x36), JMPLABEL_OPED(OPED0x37),
    JMPLABEL_OPED(OPED0x38), JMPLABEL_OPED(OPED0x39), JMPLABEL_OPED(OPED0x3a), JMPLABEL_OPED(OPED0x3b),
    JMPLABEL_OPED(OPED0x3c), JMPLABEL_OPED(OPED0x3d), JMPLABEL_OPED(OPED0x3e), JMPLABEL_OPED(OPED0x3f),

    JMPLABEL_OPED(OPED0x40), JMPLABEL_OPED(OPED0x41), JMPLABEL_OPED(OPED0x42), JMPLABEL_OPED(OPED0x43),
    JMPLABEL_OPED(OPED0x44), JMPLABEL_OPED(OPED0x45), JMPLABEL_OPED(OPED0x46), JMPLABEL_OPED(OPED0x47),
    JMPLABEL_OPED(OPED0x48), JMPLABEL_OPED(OPED0x49), JMPLABEL_OPED(OPED0x4a), JMPLABEL_OPED(OPED0x4b),
    JMPLABEL_OPED(OPED0x4c), JMPLABEL_OPED(OPED0x4d), JMPLABEL_OPED(OPED0x4e), JMPLABEL_OPED(OPED0x4f),

    JMPLABEL_OPED(OPED0x50), JMPLABEL_OPED(OPED0x51), JMPLABEL_OPED(OPED0x52), JMPLABEL_OPED(OPED0x53),
    JMPLABEL_OPED(OPED0x54), JMPLABEL_OPED(OPED0x55), JMPLABEL_OPED(OPED0x56), JMPLABEL_OPED(OPED0x57),
    JMPLABEL_OPED(OPED0x58), JMPLABEL_OPED(OPED0x59), JMPLABEL_OPED(OPED0x5a), JMPLABEL_OPED(OPED0x5b),
    JMPLABEL_OPED(OPED0x5c), JMPLABEL_OPED(OPED0x5d), JMPLABEL_OPED(OPED0x5e), JMPLABEL_OPED(OPED0x5f),

    JMPLABEL_OPED(OPED0x60), JMPLABEL_OPED(OPED0x61), JMPLABEL_OPED(OPED0x62), JMPLABEL_OPED(OPED0x63),
    JMPLABEL_OPED(OPED0x64), JMPLABEL_OPED(OPED0x65), JMPLABEL_OPED(OPED0x66), JMPLABEL_OPED(OPED0x67),
    JMPLABEL_OPED(OPED0x68), JMPLABEL_OPED(OPED0x69), JMPLABEL_OPED(OPED0x6a), JMPLABEL_OPED(OPED0x6b),
    JMPLABEL_OPED(OPED0x6c), JMPLABEL_OPED(OPED0x6d), JMPLABEL_OPED(OPED0x6e), JMPLABEL_OPED(OPED0x6f),

    JMPLABEL_OPED(OPED0x70), JMPLABEL_OPED(OPED0x71), JMPLABEL_OPED(OPED0x72), JMPLABEL_OPED(OPED0x73),
    JMPLABEL_OPED(OPED0x74), JMPLABEL_OPED(OPED0x75), JMPLABEL_OPED(OPED0x76), JMPLABEL_OPED(OPED0x77),
    JMPLABEL_OPED(OPED0x78), JMPLABEL_OPED(OPED0x79), JMPLABEL_OPED(OPED0x7a), JMPLABEL_OPED(OPED0x7b),
    JMPLABEL_OPED(OPED0x7c), JMPLABEL_OPED(OPED0x7d), JMPLABEL_OPED(OPED0x7e), JMPLABEL_OPED(OPED0x7f),

    JMPLABEL_OPED(OPED0x80), JMPLABEL_OPED(OPED0x81), JMPLABEL_OPED(OPED0x82), JMPLABEL_OPED(OPED0x83),
    JMPLABEL_OPED(OPED0x84), JMPLABEL_OPED(OPED0x85), JMPLABEL_OPED(OPED0x86), JMPLABEL_OPED(OPED0x87),
    JMPLABEL_OPED(OPED0x88), JMPLABEL_OPED(OPED0x89), JMPLABEL_OPED(OPED0x8a), JMPLABEL_OPED(OPED0x8b),
    JMPLABEL_OPED(OPED0x8c), JMPLABEL_OPED(OPED0x8d), JMPLABEL_OPED(OPED0x8e), JMPLABEL_OPED(OPED0x8f),

    JMPLABEL_OPED(OPED0x90), JMPLABEL_OPED(OPED0x91), JMPLABEL_OPED(OPED0x92), JMPLABEL_OPED(OPED0x93),
    JMPLABEL_OPED(OPED0x94), JMPLABEL_OPED(OPED0x95), JMPLABEL_OPED(OPED0x96), JMPLABEL_OPED(OPED0x97),
    JMPLABEL_OPED(OPED0x98), JMPLABEL_OPED(OPED0x99), JMPLABEL_OPED(OPED0x9a), JMPLABEL_OPED(OPED0x9b),
    JMPLABEL_OPED(OPED0x9c), JMPLABEL_OPED(OPED0x9d), JMPLABEL_OPED(OPED0x9e), JMPLABEL_OPED(OPED0x9f),

    JMPLABEL_OPED(OPED0xa0), JMPLABEL_OPED(OPED0xa1), JMPLABEL_OPED(OPED0xa2), JMPLABEL_OPED(OPED0xa3),
    JMPLABEL_OPED(OPED0xa4), JMPLABEL_OPED(OPED0xa5), JMPLABEL_OPED(OPED0xa6), JMPLABEL_OPED(OPED0xa7),
    JMPLABEL_OPED(OPED0xa8), JMPLABEL_OPED(OPED0xa9), JMPLABEL_OPED(OPED0xaa), JMPLABEL_OPED(OPED0xab),
    JMPLABEL_OPED(OPED0xac), JMPLABEL_OPED(OPED0xad), JMPLABEL_OPED(OPED0xae), JMPLABEL_OPED(OPED0xaf),

    JMPLABEL_OPED(OPED0xb0), JMPLABEL_OPED(OPED0xb1), JMPLABEL_OPED(OPED0xb2), JMPLABEL_OPED(OPED0xb3),
    JMPLABEL_OPED(OPED0xb4), JMPLABEL_OPED(OPED0xb5), JMPLABEL_OPED(OPED0xb6), JMPLABEL_OPED(OPED0xb7),
    JMPLABEL_OPED(OPED0xb8), JMPLABEL_OPED(OPED0xb9), JMPLABEL_OPED(OPED0xba), JMPLABEL_OPED(OPED0xbb),
    JMPLABEL_OPED(OPED0xbc), JMPLABEL_OPED(OPED0xbd), JMPLABEL_OPED(OPED0xbe), JMPLABEL_OPED(OPED0xbf),

    JMPLABEL_OPED(OPED0xc0), JMPLABEL_OPED(OPED0xc1), JMPLABEL_OPED(OPED0xc2), JMPLABEL_OPED(OPED0xc3),
    JMPLABEL_OPED(OPED0xc4), JMPLABEL_OPED(OPED0xc5), JMPLABEL_OPED(OPED0xc6), JMPLABEL_OPED(OPED0xc7),
    JMPLABEL_OPED(OPED0xc8), JMPLABEL_OPED(OPED0xc9), JMPLABEL_OPED(OPED0xca), JMPLABEL_OPED(OPED0xcb),
    JMPLABEL_OPED(OPED0xcc), JMPLABEL_OPED(OPED0xcd), JMPLABEL_OPED(OPED0xce), JMPLABEL_OPED(OPED0xcf),

    JMPLABEL_OPED(OPED0xd0), JMPLABEL_OPED(OPED0xd1), JMPLABEL_OPED(OPED0xd2), JMPLABEL_OPED(OPED0xd3),
    JMPLABEL_OPED(OPED0xd4), JMPLABEL_OPED(OPED0xd5), JMPLABEL_OPED(OPED0xd6), JMPLABEL_OPED(OPED0xd7),
    JMPLABEL_OPED(OPED0xd8), JMPLABEL_OPED(OPED0xd9), JMPLABEL_OPED(OPED0xda), JMPLABEL_OPED(OPED0xdb),
    JMPLABEL_OPED(OPED0xdc), JMPLABEL_OPED(OPED0xdd), JMPLABEL_OPED(OPED0xde), JMPLABEL_OPED(OPED0xdf),

    JMPLABEL_OPED(OPED0xe0), JMPLABEL_OPED(OPED0xe1), JMPLABEL_OPED(OPED0xe2), JMPLABEL_OPED(OPED0xe3),
    JMPLABEL_OPED(OPED0xe4), JMPLABEL_OPED(OPED0xe5), JMPLABEL_OPED(OPED0xe6), JMPLABEL_OPED(OPED0xe7),
    JMPLABEL_OPED(OPED0xe8), JMPLABEL_OPED(OPED0xe9), JMPLABEL_OPED(OPED0xea), JMPLABEL_OPED(OPED0xeb),
    JMPLABEL_OPED(OPED0xec), JMPLABEL_OPED(OPED0xed), JMPLABEL_OPED(OPED0xee), JMPLABEL_OPED(OPED0xef),

    JMPLABEL_OPED(OPED0xf0), JMPLABEL_OPED(OPED0xf1), JMPLABEL_OPED(OPED0xf2), JMPLABEL_OPED(OPED0xf3),
    JMPLABEL_OPED(OPED0xf4), JMPLABEL_OPED(OPED0xf5), JMPLABEL_OPED(OPED0xf6), JMPLABEL_OPED(OPED0xf7),
    JMPLABEL_OPED(OPED0xf8), JMPLABEL_OPED(OPED0xf9), JMPLABEL_OPED(OPED0xfa), JMPLABEL_OPED(OPED0xfb),
    JMPLABEL_OPED(OPED0xfc), JMPLABEL_OPED(OPED0xfd), JMPLABEL_OPED(OPED0xfe), JMPLABEL_OPED(OPED0xff)
};

#define JMPLABEL_OPXY(label) JMPTBL(OPXY0x00, label)
#define DO_JMPTBL_OPXY(Opcode) DO_JMPTBL(JumpTableXY, OPXY0x00, Opcode)
static const CZ80_JMPTYPE JumpTableXY[0x100] = {
    JMPLABEL_OPXY(OPXY0x00), JMPLABEL_OPXY(OPXY0x01), JMPLABEL_OPXY(OPXY0x02), JMPLABEL_OPXY(OPXY0x03),
    JMPLABEL_OPXY(OPXY0x04), JMPLABEL_OPXY(OPXY0x05), JMPLABEL_OPXY(OPXY0x06), JMPLABEL_OPXY(OPXY0x07),
    JMPLABEL_OPXY(OPXY0x08), JMPLABEL_OPXY(OPXY0x09), JMPLABEL_OPXY(OPXY0x0a), JMPLABEL_OPXY(OPXY0x0b),
    JMPLABEL_OPXY(OPXY0x0c), JMPLABEL_OPXY(OPXY0x0d), JMPLABEL_OPXY(OPXY0x0e), JMPLABEL_OPXY(OPXY0x0f),

    JMPLABEL_OPXY(OPXY0x10), JMPLABEL_OPXY(OPXY0x11), JMPLABEL_OPXY(OPXY0x12), JMPLABEL_OPXY(OPXY0x13),
    JMPLABEL_OPXY(OPXY0x14), JMPLABEL_OPXY(OPXY0x15), JMPLABEL_OPXY(OPXY0x16), JMPLABEL_OPXY(OPXY0x17),
    JMPLABEL_OPXY(OPXY0x18), JMPLABEL_OPXY(OPXY0x19), JMPLABEL_OPXY(OPXY0x1a), JMPLABEL_OPXY(OPXY0x1b),
    JMPLABEL_OPXY(OPXY0x1c), JMPLABEL_OPXY(OPXY0x1d), JMPLABEL_OPXY(OPXY0x1e), JMPLABEL_OPXY(OPXY0x1f),

    JMPLABEL_OPXY(OPXY0x20), JMPLABEL_OPXY(OPXY0x21), JMPLABEL_OPXY(OPXY0x22), JMPLABEL_OPXY(OPXY0x23),
    JMPLABEL_OPXY(OPXY0x24), JMPLABEL_OPXY(OPXY0x25), JMPLABEL_OPXY(OPXY0x26), JMPLABEL_OPXY(OPXY0x27),
    JMPLABEL_OPXY(OPXY0x28), JMPLABEL_OPXY(OPXY0x29), JMPLABEL_OPXY(OPXY0x2a), JMPLABEL_OPXY(OPXY0x2b),
    JMPLABEL_OPXY(OPXY0x2c), JMPLABEL_OPXY(OPXY0x2d), JMPLABEL_OPXY(OPXY0x2e), JMPLABEL_OPXY(OPXY0x2f),

    JMPLABEL_OPXY(OPXY0x30), JMPLABEL_OPXY(OPXY0x31), JMPLABEL_OPXY(OPXY0x32), JMPLABEL_OPXY(OPXY0x33),
    JMPLABEL_OPXY(OPXY0x34), JMPLABEL_OPXY(OPXY0x35), JMPLABEL_OPXY(OPXY0x36), JMPLABEL_OPXY(OPXY0x37),
    JMPLABEL_OPXY(OPXY0x38), JMPLABEL_OPXY(OPXY0x39), JMPLABEL_OPXY(OPXY0x3a), JMPLABEL_OPXY(OPXY0x3b),
    JMPLABEL_OPXY(OPXY0x3c), JMPLABEL_OPXY(OPXY0x3d), JMPLABEL_OPXY(OPXY0x3e), JMPLABEL_OPXY(OPXY0x3f),

    JMPLABEL_OPXY(OPXY0x40), JMPLABEL_OPXY(OPXY0x41), JMPLABEL_OPXY(OPXY0x42), JMPLABEL_OPXY(OPXY0x43),
    JMPLABEL_OPXY(OPXY0x44), JMPLABEL_OPXY(OPXY0x45), JMPLABEL_OPXY(OPXY0x46), JMPLABEL_OPXY(OPXY0x47),
    JMPLABEL_OPXY(OPXY0x48), JMPLABEL_OPXY(OPXY0x49), JMPLABEL_OPXY(OPXY0x4a), JMPLABEL_OPXY(OPXY0x4b),
    JMPLABEL_OPXY(OPXY0x4c), JMPLABEL_OPXY(OPXY0x4d), JMPLABEL_OPXY(OPXY0x4e), JMPLABEL_OPXY(OPXY0x4f),

    JMPLABEL_OPXY(OPXY0x50), JMPLABEL_OPXY(OPXY0x51), JMPLABEL_OPXY(OPXY0x52), JMPLABEL_OPXY(OPXY0x53),
    JMPLABEL_OPXY(OPXY0x54), JMPLABEL_OPXY(OPXY0x55), JMPLABEL_OPXY(OPXY0x56), JMPLABEL_OPXY(OPXY0x57),
    JMPLABEL_OPXY(OPXY0x58), JMPLABEL_OPXY(OPXY0x59), JMPLABEL_OPXY(OPXY0x5a), JMPLABEL_OPXY(OPXY0x5b),
    JMPLABEL_OPXY(OPXY0x5c), JMPLABEL_OPXY(OPXY0x5d), JMPLABEL_OPXY(OPXY0x5e), JMPLABEL_OPXY(OPXY0x5f),

    JMPLABEL_OPXY(OPXY0x60), JMPLABEL_OPXY(OPXY0x61), JMPLABEL_OPXY(OPXY0x62), JMPLABEL_OPXY(OPXY0x63),
    JMPLABEL_OPXY(OPXY0x64), JMPLABEL_OPXY(OPXY0x65), JMPLABEL_OPXY(OPXY0x66), JMPLABEL_OPXY(OPXY0x67),
    JMPLABEL_OPXY(OPXY0x68), JMPLABEL_OPXY(OPXY0x69), JMPLABEL_OPXY(OPXY0x6a), JMPLABEL_OPXY(OPXY0x6b),
    JMPLABEL_OPXY(OPXY0x6c), JMPLABEL_OPXY(OPXY0x6d), JMPLABEL_OPXY(OPXY0x6e), JMPLABEL_OPXY(OPXY0x6f),

    JMPLABEL_OPXY(OPXY0x70), JMPLABEL_OPXY(OPXY0x71), JMPLABEL_OPXY(OPXY0x72), JMPLABEL_OPXY(OPXY0x73),
    JMPLABEL_OPXY(OPXY0x74), JMPLABEL_OPXY(OPXY0x75), JMPLABEL_OPXY(OPXY0x76), JMPLABEL_OPXY(OPXY0x77),
    JMPLABEL_OPXY(OPXY0x78), JMPLABEL_OPXY(OPXY0x79), JMPLABEL_OPXY(OPXY0x7a), JMPLABEL_OPXY(OPXY0x7b),
    JMPLABEL_OPXY(OPXY0x7c), JMPLABEL_OPXY(OPXY0x7d), JMPLABEL_OPXY(OPXY0x7e), JMPLABEL_OPXY(OPXY0x7f),

    JMPLABEL_OPXY(OPXY0x80), JMPLABEL_OPXY(OPXY0x81), JMPLABEL_OPXY(OPXY0x82), JMPLABEL_OPXY(OPXY0x83),
    JMPLABEL_OPXY(OPXY0x84), JMPLABEL_OPXY(OPXY0x85), JMPLABEL_OPXY(OPXY0x86), JMPLABEL_OPXY(OPXY0x87),
    JMPLABEL_OPXY(OPXY0x88), JMPLABEL_OPXY(OPXY0x89), JMPLABEL_OPXY(OPXY0x8a), JMPLABEL_OPXY(OPXY0x8b),
    JMPLABEL_OPXY(OPXY0x8c), JMPLABEL_OPXY(OPXY0x8d), JMPLABEL_OPXY(OPXY0x8e), JMPLABEL_OPXY(OPXY0x8f),

    JMPLABEL_OPXY(OPXY0x90), JMPLABEL_OPXY(OPXY0x91), JMPLABEL_OPXY(OPXY0x92), JMPLABEL_OPXY(OPXY0x93),
    JMPLABEL_OPXY(OPXY0x94), JMPLABEL_OPXY(OPXY0x95), JMPLABEL_OPXY(OPXY0x96), JMPLABEL_OPXY(OPXY0x97),
    JMPLABEL_OPXY(OPXY0x98), JMPLABEL_OPXY(OPXY0x99), JMPLABEL_OPXY(OPXY0x9a), JMPLABEL_OPXY(OPXY0x9b),
    JMPLABEL_OPXY(OPXY0x9c), JMPLABEL_OPXY(OPXY0x9d), JMPLABEL_OPXY(OPXY0x9e), JMPLABEL_OPXY(OPXY0x9f),

    JMPLABEL_OPXY(OPXY0xa0), JMPLABEL_OPXY(OPXY0xa1), JMPLABEL_OPXY(OPXY0xa2), JMPLABEL_OPXY(OPXY0xa3),
    JMPLABEL_OPXY(OPXY0xa4), JMPLABEL_OPXY(OPXY0xa5), JMPLABEL_OPXY(OPXY0xa6), JMPLABEL_OPXY(OPXY0xa7),
    JMPLABEL_OPXY(OPXY0xa8), JMPLABEL_OPXY(OPXY0xa9), JMPLABEL_OPXY(OPXY0xaa), JMPLABEL_OPXY(OPXY0xab),
    JMPLABEL_OPXY(OPXY0xac), JMPLABEL_OPXY(OPXY0xad), JMPLABEL_OPXY(OPXY0xae), JMPLABEL_OPXY(OPXY0xaf),

    JMPLABEL_OPXY(OPXY0xb0), JMPLABEL_OPXY(OPXY0xb1), JMPLABEL_OPXY(OPXY0xb2), JMPLABEL_OPXY(OPXY0xb3),
    JMPLABEL_OPXY(OPXY0xb4), JMPLABEL_OPXY(OPXY0xb5), JMPLABEL_OPXY(OPXY0xb6), JMPLABEL_OPXY(OPXY0xb7),
    JMPLABEL_OPXY(OPXY0xb8), JMPLABEL_OPXY(OPXY0xb9), JMPLABEL_OPXY(OPXY0xba), JMPLABEL_OPXY(OPXY0xbb),
    JMPLABEL_OPXY(OPXY0xbc), JMPLABEL_OPXY(OPXY0xbd), JMPLABEL_OPXY(OPXY0xbe), JMPLABEL_OPXY(OPXY0xbf),

    JMPLABEL_OPXY(OPXY0xc0), JMPLABEL_OPXY(OPXY0xc1), JMPLABEL_OPXY(OPXY0xc2), JMPLABEL_OPXY(OPXY0xc3),
    JMPLABEL_OPXY(OPXY0xc4), JMPLABEL_OPXY(OPXY0xc5), JMPLABEL_OPXY(OPXY0xc6), JMPLABEL_OPXY(OPXY0xc7),
    JMPLABEL_OPXY(OPXY0xc8), JMPLABEL_OPXY(OPXY0xc9), JMPLABEL_OPXY(OPXY0xca), JMPLABEL_OPXY(OPXY0xcb),
    JMPLABEL_OPXY(OPXY0xcc), JMPLABEL_OPXY(OPXY0xcd), JMPLABEL_OPXY(OPXY0xce), JMPLABEL_OPXY(OPXY0xcf),

    JMPLABEL_OPXY(OPXY0xd0), JMPLABEL_OPXY(OPXY0xd1), JMPLABEL_OPXY(OPXY0xd2), JMPLABEL_OPXY(OPXY0xd3),
    JMPLABEL_OPXY(OPXY0xd4), JMPLABEL_OPXY(OPXY0xd5), JMPLABEL_OPXY(OPXY0xd6), JMPLABEL_OPXY(OPXY0xd7),
    JMPLABEL_OPXY(OPXY0xd8), JMPLABEL_OPXY(OPXY0xd9), JMPLABEL_OPXY(OPXY0xda), JMPLABEL_OPXY(OPXY0xdb),
    JMPLABEL_OPXY(OPXY0xdc), JMPLABEL_OPXY(OPXY0xdd), JMPLABEL_OPXY(OPXY0xde), JMPLABEL_OPXY(OPXY0xdf),

    JMPLABEL_OPXY(OPXY0xe0), JMPLABEL_OPXY(OPXY0xe1), JMPLABEL_OPXY(OPXY0xe2), JMPLABEL_OPXY(OPXY0xe3),
    JMPLABEL_OPXY(OPXY0xe4), JMPLABEL_OPXY(OPXY0xe5), JMPLABEL_OPXY(OPXY0xe6), JMPLABEL_OPXY(OPXY0xe7),
    JMPLABEL_OPXY(OPXY0xe8), JMPLABEL_OPXY(OPXY0xe9), JMPLABEL_OPXY(OPXY0xea), JMPLABEL_OPXY(OPXY0xeb),
    JMPLABEL_OPXY(OPXY0xec), JMPLABEL_OPXY(OPXY0xed), JMPLABEL_OPXY(OPXY0xee), JMPLABEL_OPXY(OPXY0xef),

    JMPLABEL_OPXY(OPXY0xf0), JMPLABEL_OPXY(OPXY0xf1), JMPLABEL_OPXY(OPXY0xf2), JMPLABEL_OPXY(OPXY0xf3),
    JMPLABEL_OPXY(OPXY0xf4), JMPLABEL_OPXY(OPXY0xf5), JMPLABEL_OPXY(OPXY0xf6), JMPLABEL_OPXY(OPXY0xf7),
    JMPLABEL_OPXY(OPXY0xf8), JMPLABEL_OPXY(OPXY0xf9), JMPLABEL_OPXY(OPXY0xfa), JMPLABEL_OPXY(OPXY0xfb),
    JMPLABEL_OPXY(OPXY0xfc), JMPLABEL_OPXY(OPXY0xfd), JMPLABEL_OPXY(OPXY0xfe), JMPLABEL_OPXY(OPXY0xff)
};

#define JMPLABEL_OPXYCB(label) JMPTBL(OPXYCB0x00, label)
#define DO_JMPTBL_OPXYCB(Opcode) DO_JMPTBL(JumpTableXYCB, OPXYCB0x00, Opcode)
static const CZ80_JMPTYPE JumpTableXYCB[0x100] = {
    JMPLABEL_OPXYCB(OPXYCB0x00), JMPLABEL_OPXYCB(OPXYCB0x01), JMPLABEL_OPXYCB(OPXYCB0x02), JMPLABEL_OPXYCB(OPXYCB0x03),
    JMPLABEL_OPXYCB(OPXYCB0x04), JMPLABEL_OPXYCB(OPXYCB0x05), JMPLABEL_OPXYCB(OPXYCB0x06), JMPLABEL_OPXYCB(OPXYCB0x07),
    JMPLABEL_OPXYCB(OPXYCB0x08), JMPLABEL_OPXYCB(OPXYCB0x09), JMPLABEL_OPXYCB(OPXYCB0x0a), JMPLABEL_OPXYCB(OPXYCB0x0b),
    JMPLABEL_OPXYCB(OPXYCB0x0c), JMPLABEL_OPXYCB(OPXYCB0x0d), JMPLABEL_OPXYCB(OPXYCB0x0e), JMPLABEL_OPXYCB(OPXYCB0x0f),

    JMPLABEL_OPXYCB(OPXYCB0x10), JMPLABEL_OPXYCB(OPXYCB0x11), JMPLABEL_OPXYCB(OPXYCB0x12), JMPLABEL_OPXYCB(OPXYCB0x13),
    JMPLABEL_OPXYCB(OPXYCB0x14), JMPLABEL_OPXYCB(OPXYCB0x15), JMPLABEL_OPXYCB(OPXYCB0x16), JMPLABEL_OPXYCB(OPXYCB0x17),
    JMPLABEL_OPXYCB(OPXYCB0x18), JMPLABEL_OPXYCB(OPXYCB0x19), JMPLABEL_OPXYCB(OPXYCB0x1a), JMPLABEL_OPXYCB(OPXYCB0x1b),
    JMPLABEL_OPXYCB(OPXYCB0x1c), JMPLABEL_OPXYCB(OPXYCB0x1d), JMPLABEL_OPXYCB(OPXYCB0x1e), JMPLABEL_OPXYCB(OPXYCB0x1f),

    JMPLABEL_OPXYCB(OPXYCB0x20), JMPLABEL_OPXYCB(OPXYCB0x21), JMPLABEL_OPXYCB(OPXYCB0x22), JMPLABEL_OPXYCB(OPXYCB0x23),
    JMPLABEL_OPXYCB(OPXYCB0x24), JMPLABEL_OPXYCB(OPXYCB0x25), JMPLABEL_OPXYCB(OPXYCB0x26), JMPLABEL_OPXYCB(OPXYCB0x27),
    JMPLABEL_OPXYCB(OPXYCB0x28), JMPLABEL_OPXYCB(OPXYCB0x29), JMPLABEL_OPXYCB(OPXYCB0x2a), JMPLABEL_OPXYCB(OPXYCB0x2b),
    JMPLABEL_OPXYCB(OPXYCB0x2c), JMPLABEL_OPXYCB(OPXYCB0x2d), JMPLABEL_OPXYCB(OPXYCB0x2e), JMPLABEL_OPXYCB(OPXYCB0x2f),

    JMPLABEL_OPXYCB(OPXYCB0x30), JMPLABEL_OPXYCB(OPXYCB0x31), JMPLABEL_OPXYCB(OPXYCB0x32), JMPLABEL_OPXYCB(OPXYCB0x33),
    JMPLABEL_OPXYCB(OPXYCB0x34), JMPLABEL_OPXYCB(OPXYCB0x35), JMPLABEL_OPXYCB(OPXYCB0x36), JMPLABEL_OPXYCB(OPXYCB0x37),
    JMPLABEL_OPXYCB(OPXYCB0x38), JMPLABEL_OPXYCB(OPXYCB0x39), JMPLABEL_OPXYCB(OPXYCB0x3a), JMPLABEL_OPXYCB(OPXYCB0x3b),
    JMPLABEL_OPXYCB(OPXYCB0x3c), JMPLABEL_OPXYCB(OPXYCB0x3d), JMPLABEL_OPXYCB(OPXYCB0x3e), JMPLABEL_OPXYCB(OPXYCB0x3f),

    JMPLABEL_OPXYCB(OPXYCB0x40), JMPLABEL_OPXYCB(OPXYCB0x41), JMPLABEL_OPXYCB(OPXYCB0x42), JMPLABEL_OPXYCB(OPXYCB0x43),
    JMPLABEL_OPXYCB(OPXYCB0x44), JMPLABEL_OPXYCB(OPXYCB0x45), JMPLABEL_OPXYCB(OPXYCB0x46), JMPLABEL_OPXYCB(OPXYCB0x47),
    JMPLABEL_OPXYCB(OPXYCB0x48), JMPLABEL_OPXYCB(OPXYCB0x49), JMPLABEL_OPXYCB(OPXYCB0x4a), JMPLABEL_OPXYCB(OPXYCB0x4b),
    JMPLABEL_OPXYCB(OPXYCB0x4c), JMPLABEL_OPXYCB(OPXYCB0x4d), JMPLABEL_OPXYCB(OPXYCB0x4e), JMPLABEL_OPXYCB(OPXYCB0x4f),

    JMPLABEL_OPXYCB(OPXYCB0x50), JMPLABEL_OPXYCB(OPXYCB0x51), JMPLABEL_OPXYCB(OPXYCB0x52), JMPLABEL_OPXYCB(OPXYCB0x53),
    JMPLABEL_OPXYCB(OPXYCB0x54), JMPLABEL_OPXYCB(OPXYCB0x55), JMPLABEL_OPXYCB(OPXYCB0x56), JMPLABEL_OPXYCB(OPXYCB0x57),
    JMPLABEL_OPXYCB(OPXYCB0x58), JMPLABEL_OPXYCB(OPXYCB0x59), JMPLABEL_OPXYCB(OPXYCB0x5a), JMPLABEL_OPXYCB(OPXYCB0x5b),
    JMPLABEL_OPXYCB(OPXYCB0x5c), JMPLABEL_OPXYCB(OPXYCB0x5d), JMPLABEL_OPXYCB(OPXYCB0x5e), JMPLABEL_OPXYCB(OPXYCB0x5f),

    JMPLABEL_OPXYCB(OPXYCB0x60), JMPLABEL_OPXYCB(OPXYCB0x61), JMPLABEL_OPXYCB(OPXYCB0x62), JMPLABEL_OPXYCB(OPXYCB0x63),
    JMPLABEL_OPXYCB(OPXYCB0x64), JMPLABEL_OPXYCB(OPXYCB0x65), JMPLABEL_OPXYCB(OPXYCB0x66), JMPLABEL_OPXYCB(OPXYCB0x67),
    JMPLABEL_OPXYCB(OPXYCB0x68), JMPLABEL_OPXYCB(OPXYCB0x69), JMPLABEL_OPXYCB(OPXYCB0x6a), JMPLABEL_OPXYCB(OPXYCB0x6b),
    JMPLABEL_OPXYCB(OPXYCB0x6c), JMPLABEL_OPXYCB(OPXYCB0x6d), JMPLABEL_OPXYCB(OPXYCB0x6e), JMPLABEL_OPXYCB(OPXYCB0x6f),

    JMPLABEL_OPXYCB(OPXYCB0x70), JMPLABEL_OPXYCB(OPXYCB0x71), JMPLABEL_OPXYCB(OPXYCB0x72), JMPLABEL_OPXYCB(OPXYCB0x73),
    JMPLABEL_OPXYCB(OPXYCB0x74), JMPLABEL_OPXYCB(OPXYCB0x75), JMPLABEL_OPXYCB(OPXYCB0x76), JMPLABEL_OPXYCB(OPXYCB0x77),
    JMPLABEL_OPXYCB(OPXYCB0x78), JMPLABEL_OPXYCB(OPXYCB0x79), JMPLABEL_OPXYCB(OPXYCB0x7a), JMPLABEL_OPXYCB(OPXYCB0x7b),
    JMPLABEL_OPXYCB(OPXYCB0x7c), JMPLABEL_OPXYCB(OPXYCB0x7d), JMPLABEL_OPXYCB(OPXYCB0x7e), JMPLABEL_OPXYCB(OPXYCB0x7f),

    JMPLABEL_OPXYCB(OPXYCB0x80), JMPLABEL_OPXYCB(OPXYCB0x81), JMPLABEL_OPXYCB(OPXYCB0x82), JMPLABEL_OPXYCB(OPXYCB0x83),
    JMPLABEL_OPXYCB(OPXYCB0x84), JMPLABEL_OPXYCB(OPXYCB0x85), JMPLABEL_OPXYCB(OPXYCB0x86), JMPLABEL_OPXYCB(OPXYCB0x87),
    JMPLABEL_OPXYCB(OPXYCB0x88), JMPLABEL_OPXYCB(OPXYCB0x89), JMPLABEL_OPXYCB(OPXYCB0x8a), JMPLABEL_OPXYCB(OPXYCB0x8b),
    JMPLABEL_OPXYCB(OPXYCB0x8c), JMPLABEL_OPXYCB(OPXYCB0x8d), JMPLABEL_OPXYCB(OPXYCB0x8e), JMPLABEL_OPXYCB(OPXYCB0x8f),

    JMPLABEL_OPXYCB(OPXYCB0x90), JMPLABEL_OPXYCB(OPXYCB0x91), JMPLABEL_OPXYCB(OPXYCB0x92), JMPLABEL_OPXYCB(OPXYCB0x93),
    JMPLABEL_OPXYCB(OPXYCB0x94), JMPLABEL_OPXYCB(OPXYCB0x95), JMPLABEL_OPXYCB(OPXYCB0x96), JMPLABEL_OPXYCB(OPXYCB0x97),
    JMPLABEL_OPXYCB(OPXYCB0x98), JMPLABEL_OPXYCB(OPXYCB0x99), JMPLABEL_OPXYCB(OPXYCB0x9a), JMPLABEL_OPXYCB(OPXYCB0x9b),
    JMPLABEL_OPXYCB(OPXYCB0x9c), JMPLABEL_OPXYCB(OPXYCB0x9d), JMPLABEL_OPXYCB(OPXYCB0x9e), JMPLABEL_OPXYCB(OPXYCB0x9f),

    JMPLABEL_OPXYCB(OPXYCB0xa0), JMPLABEL_OPXYCB(OPXYCB0xa1), JMPLABEL_OPXYCB(OPXYCB0xa2), JMPLABEL_OPXYCB(OPXYCB0xa3),
    JMPLABEL_OPXYCB(OPXYCB0xa4), JMPLABEL_OPXYCB(OPXYCB0xa5), JMPLABEL_OPXYCB(OPXYCB0xa6), JMPLABEL_OPXYCB(OPXYCB0xa7),
    JMPLABEL_OPXYCB(OPXYCB0xa8), JMPLABEL_OPXYCB(OPXYCB0xa9), JMPLABEL_OPXYCB(OPXYCB0xaa), JMPLABEL_OPXYCB(OPXYCB0xab),
    JMPLABEL_OPXYCB(OPXYCB0xac), JMPLABEL_OPXYCB(OPXYCB0xad), JMPLABEL_OPXYCB(OPXYCB0xae), JMPLABEL_OPXYCB(OPXYCB0xaf),

    JMPLABEL_OPXYCB(OPXYCB0xb0), JMPLABEL_OPXYCB(OPXYCB0xb1), JMPLABEL_OPXYCB(OPXYCB0xb2), JMPLABEL_OPXYCB(OPXYCB0xb3),
    JMPLABEL_OPXYCB(OPXYCB0xb4), JMPLABEL_OPXYCB(OPXYCB0xb5), JMPLABEL_OPXYCB(OPXYCB0xb6), JMPLABEL_OPXYCB(OPXYCB0xb7),
    JMPLABEL_OPXYCB(OPXYCB0xb8), JMPLABEL_OPXYCB(OPXYCB0xb9), JMPLABEL_OPXYCB(OPXYCB0xba), JMPLABEL_OPXYCB(OPXYCB0xbb),
    JMPLABEL_OPXYCB(OPXYCB0xbc), JMPLABEL_OPXYCB(OPXYCB0xbd), JMPLABEL_OPXYCB(OPXYCB0xbe), JMPLABEL_OPXYCB(OPXYCB0xbf),

    JMPLABEL_OPXYCB(OPXYCB0xc0), JMPLABEL_OPXYCB(OPXYCB0xc1), JMPLABEL_OPXYCB(OPXYCB0xc2), JMPLABEL_OPXYCB(OPXYCB0xc3),
    JMPLABEL_OPXYCB(OPXYCB0xc4), JMPLABEL_OPXYCB(OPXYCB0xc5), JMPLABEL_OPXYCB(OPXYCB0xc6), JMPLABEL_OPXYCB(OPXYCB0xc7),
    JMPLABEL_OPXYCB(OPXYCB0xc8), JMPLABEL_OPXYCB(OPXYCB0xc9), JMPLABEL_OPXYCB(OPXYCB0xca), JMPLABEL_OPXYCB(OPXYCB0xcb),
    JMPLABEL_OPXYCB(OPXYCB0xcc), JMPLABEL_OPXYCB(OPXYCB0xcd), JMPLABEL_OPXYCB(OPXYCB0xce), JMPLABEL_OPXYCB(OPXYCB0xcf),

    JMPLABEL_OPXYCB(OPXYCB0xd0), JMPLABEL_OPXYCB(OPXYCB0xd1), JMPLABEL_OPXYCB(OPXYCB0xd2), JMPLABEL_OPXYCB(OPXYCB0xd3),
    JMPLABEL_OPXYCB(OPXYCB0xd4), JMPLABEL_OPXYCB(OPXYCB0xd5), JMPLABEL_OPXYCB(OPXYCB0xd6), JMPLABEL_OPXYCB(OPXYCB0xd7),
    JMPLABEL_OPXYCB(OPXYCB0xd8), JMPLABEL_OPXYCB(OPXYCB0xd9), JMPLABEL_OPXYCB(OPXYCB0xda), JMPLABEL_OPXYCB(OPXYCB0xdb),
    JMPLABEL_OPXYCB(OPXYCB0xdc), JMPLABEL_OPXYCB(OPXYCB0xdd), JMPLABEL_OPXYCB(OPXYCB0xde), JMPLABEL_OPXYCB(OPXYCB0xdf),

    JMPLABEL_OPXYCB(OPXYCB0xe0), JMPLABEL_OPXYCB(OPXYCB0xe1), JMPLABEL_OPXYCB(OPXYCB0xe2), JMPLABEL_OPXYCB(OPXYCB0xe3),
    JMPLABEL_OPXYCB(OPXYCB0xe4), JMPLABEL_OPXYCB(OPXYCB0xe5), JMPLABEL_OPXYCB(OPXYCB0xe6), JMPLABEL_OPXYCB(OPXYCB0xe7),
    JMPLABEL_OPXYCB(OPXYCB0xe8), JMPLABEL_OPXYCB(OPXYCB0xe9), JMPLABEL_OPXYCB(OPXYCB0xea), JMPLABEL_OPXYCB(OPXYCB0xeb),
    JMPLABEL_OPXYCB(OPXYCB0xec), JMPLABEL_OPXYCB(OPXYCB0xed), JMPLABEL_OPXYCB(OPXYCB0xee), JMPLABEL_OPXYCB(OPXYCB0xef),

    JMPLABEL_OPXYCB(OPXYCB0xf0), JMPLABEL_OPXYCB(OPXYCB0xf1), JMPLABEL_OPXYCB(OPXYCB0xf2), JMPLABEL_OPXYCB(OPXYCB0xf3),
    JMPLABEL_OPXYCB(OPXYCB0xf4), JMPLABEL_OPXYCB(OPXYCB0xf5), JMPLABEL_OPXYCB(OPXYCB0xf6), JMPLABEL_OPXYCB(OPXYCB0xf7),
    JMPLABEL_OPXYCB(OPXYCB0xf8), JMPLABEL_OPXYCB(OPXYCB0xf9), JMPLABEL_OPXYCB(OPXYCB0xfa), JMPLABEL_OPXYCB(OPXYCB0xfb),
    JMPLABEL_OPXYCB(OPXYCB0xfc), JMPLABEL_OPXYCB(OPXYCB0xfd), JMPLABEL_OPXYCB(OPXYCB0xfe), JMPLABEL_OPXYCB(OPXYCB0xff)
};
